# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Vernotas3p.ui'
##
## Created by: Qt User Interface Compiler version 6.3.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDoubleSpinBox, QFrame, QLabel,
    QLineEdit, QSizePolicy, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(461, 438)
        Form.setStyleSheet(u"background-color: rgb(40, 40, 40);")
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 10, 81, 16))
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.txtEstudNotasDe = QLineEdit(Form)
        self.txtEstudNotasDe.setObjectName(u"txtEstudNotasDe")
        self.txtEstudNotasDe.setGeometry(QRect(20, 30, 281, 21))
        font1 = QFont()
        font1.setPointSize(11)
        self.txtEstudNotasDe.setFont(font1)
        self.txtEstudNotasDe.setStyleSheet(u"QLineEdit{\n"
"background:transparent;\n"
"border:none;\n"
"border-bottom:1px solid white;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.txtEstudNotasDe.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.line = QFrame(Form)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 110, 441, 16))
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(3)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(180, 90, 81, 16))
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_8 = QLabel(Form)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(170, 140, 121, 16))
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.cbxActIII = QDoubleSpinBox(Form)
        self.cbxActIII.setObjectName(u"cbxActIII")
        self.cbxActIII.setGeometry(QRect(320, 160, 121, 22))
        font2 = QFont()
        font2.setFamilies([u"Arial"])
        font2.setPointSize(11)
        font2.setBold(True)
        self.cbxActIII.setFont(font2)
        self.cbxActIII.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.cbxActIII.setMaximum(10.000000000000000)
        self.cbxActII = QDoubleSpinBox(Form)
        self.cbxActII.setObjectName(u"cbxActII")
        self.cbxActII.setGeometry(QRect(170, 160, 121, 22))
        self.cbxActII.setFont(font2)
        self.cbxActII.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.cbxActII.setMaximum(10.000000000000000)
        self.label_7 = QLabel(Form)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 140, 111, 16))
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_9 = QLabel(Form)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(320, 140, 121, 16))
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.cbxAct1P1 = QDoubleSpinBox(Form)
        self.cbxAct1P1.setObjectName(u"cbxAct1P1")
        self.cbxAct1P1.setGeometry(QRect(20, 160, 121, 22))
        self.cbxAct1P1.setFont(font2)
        self.cbxAct1P1.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.cbxAct1P1.setMaximum(10.000000000000000)
        self.cbxActIII_2 = QDoubleSpinBox(Form)
        self.cbxActIII_2.setObjectName(u"cbxActIII_2")
        self.cbxActIII_2.setGeometry(QRect(320, 270, 121, 22))
        self.cbxActIII_2.setFont(font2)
        self.cbxActIII_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.cbxActIII_2.setMaximum(10.000000000000000)
        self.cbxActI_2 = QDoubleSpinBox(Form)
        self.cbxActI_2.setObjectName(u"cbxActI_2")
        self.cbxActI_2.setGeometry(QRect(20, 270, 121, 22))
        self.cbxActI_2.setFont(font2)
        self.cbxActI_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.cbxActI_2.setMaximum(10.000000000000000)
        self.label_10 = QLabel(Form)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(320, 250, 121, 16))
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(185, 200, 81, 16))
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_11 = QLabel(Form)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 250, 111, 16))
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.cbxActII_2 = QDoubleSpinBox(Form)
        self.cbxActII_2.setObjectName(u"cbxActII_2")
        self.cbxActII_2.setGeometry(QRect(170, 270, 121, 22))
        self.cbxActII_2.setFont(font2)
        self.cbxActII_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.cbxActII_2.setMaximum(10.000000000000000)
        self.line_2 = QFrame(Form)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(10, 220, 441, 16))
        self.line_2.setLineWidth(1)
        self.line_2.setMidLineWidth(3)
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.label_12 = QLabel(Form)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(170, 250, 121, 16))
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.cbxActIII_3 = QDoubleSpinBox(Form)
        self.cbxActIII_3.setObjectName(u"cbxActIII_3")
        self.cbxActIII_3.setGeometry(QRect(320, 370, 121, 22))
        self.cbxActIII_3.setFont(font2)
        self.cbxActIII_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.cbxActIII_3.setMaximum(10.000000000000000)
        self.cbxActI_3 = QDoubleSpinBox(Form)
        self.cbxActI_3.setObjectName(u"cbxActI_3")
        self.cbxActI_3.setGeometry(QRect(20, 370, 121, 22))
        self.cbxActI_3.setFont(font2)
        self.cbxActI_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.cbxActI_3.setMaximum(10.000000000000000)
        self.label_13 = QLabel(Form)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(320, 350, 121, 16))
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_4 = QLabel(Form)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(185, 300, 81, 16))
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_14 = QLabel(Form)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 350, 111, 16))
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.cbxActII_3 = QDoubleSpinBox(Form)
        self.cbxActII_3.setObjectName(u"cbxActII_3")
        self.cbxActII_3.setGeometry(QRect(170, 370, 121, 22))
        self.cbxActII_3.setFont(font2)
        self.cbxActII_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.cbxActII_3.setMaximum(10.000000000000000)
        self.line_3 = QFrame(Form)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(10, 320, 441, 16))
        self.line_3.setLineWidth(1)
        self.line_3.setMidLineWidth(3)
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.label_15 = QLabel(Form)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(170, 350, 121, 16))
        self.label_15.setFont(font)
        self.label_15.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label.setText(QCoreApplication.translate("Form", u"Notas de", None))
        self.txtEstudNotasDe.setText("")
        self.txtEstudNotasDe.setPlaceholderText(QCoreApplication.translate("Form", u"Juan Perez", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Periodo I", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"Act II (35%)", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"Act I (35%)", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"Act III (30%)", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"Act III (30%)", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"Periodo II", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"Act I (35%)", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"Act II (35%)", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"Act III (30%)", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"Periodo III", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"Act I (35%)", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"Act II (35%)", None))
    # retranslateUi

